services:
  pop3:
    build: ./dovecot 
    image: eftechcombr/dovecot:latest
    restart: unless-stopped
    ports:
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
    env_file: ./.env

